### ISSUE TITLE
Netlify

### ISSUE THREAD

**Issue by JonahAragon** [danarel/thinkprivacy#10]
What are your thoughts on Netlify, specifically their use of Amazon AWS for their infrastructure? That's the main reason we didn't go with Netlify or GitHub Pages for hosting (https://github.com/privacytoolsIO/privacytools.io/issues/374#issuecomment-478067290).

Considering other providers may be out of scope for this project because Netlify works and it's hard to find a good gratis host, but I figured I'd ask since you *did* remove Cloudflare (#5).

**Comment by danarel** [comment]
I am not in love with it, I don't like that they use AWS, but right now it gives me a super easy to deploy setup. 

What is PTIO using?

**Comment by JonahAragon** [comment]
Yeah, Netlify is super convenient, we *are* using it at PTIO for the Pull Request checks and previews but our production site isn't on Netlify. We're using our own servers, or rather my own [hosting company](https://nablahost.com/) for all our public-facing infrastructure.

**Comment by danarel** [comment]
Is your github commits being pushed live to your servers? The main reason I moved to Netlify was that I could just commit and know it would go live.

**Comment by JonahAragon** [comment]
Yeah we’re using GitHub’s webhooks and [Webhook](https://github.com/adnanh/webhook) to run the build script on every commit.

**Comment by danarel** [comment]
Okay cool. I will have to look into setting that up and get off Netlify.

**Comment by danarel** [comment]
ThinkPrivacy no longer uses Netlify as the main host, only for previewing builds. Thanks @JonahAragon for the help!
