### ISSUE TITLE
Add Brave Rewards to support site

### ISSUE THREAD

**Issue by Perelandra0x309** [danarel/thinkprivacy#13]
I noticed you are a Brave Verified Publisher but that is not listed on your support webpage.

**Comment by danarel** [comment]
I signed up for that when Brave was a bit newer. Now that I know more about Brave, I will not add it to the site. It's co-creator/founder is an anti-LTGBTQ bigot, and the browser is honestly nothing more than a scheme to fund their advertising venture and sell worthless crypocurrency.
