### ISSUE TITLE
[DNS] DNSCloak for iOS

### ISSUE THREAD

**Issue by nitrohorse** [danarel/thinkprivacy#14]
Maybe worth adding the [TestFlight link](https://testflight.apple.com/join/RlMeZBo7) (appears open still) to the DNSCloak's card in https://www.thinkprivacy.ch/dns/. I'm assuming that [the developer](https://github.com/s-s) can't push any updates to the [AppStore listing](https://apps.apple.com/us/app/dnscloak-secure-dns-client/id1452162351) for whatever reason because the official link is outdated by I think ~1 year while they maintain the TestFlight build regularly from my observation. Sometimes it expires for days and then the TestFlight listing is re-added.

I suppose another related concern is that although the app is still maintained through TestFlight, [the source code](https://github.com/s-s/dnscloak) hasn't been maintained. So it's questionable if DNSCloak continues to be deemed open-source as of now.

**Comment by nitrohorse** [comment]
Other DNS options that I use myself are [AdGuard Pro](https://apps.apple.com/us/app/adguard-pro-adblock-privacy/id1126386264) which supports 3rd party DNSCrypt, DoH, and DoT resolvers or using the [iOS 14+ built-in DNS resolving functionality](https://paulmillr.com/posts/encrypted-dns/). I maintain iOS 14+ profiles over at https://encrypted-dns.party/ but an app like [DNSecure](https://github.com/kkk669/DNSecure) is likely more friendly due to the ability to use custom, updatable profiles through the app.

Worth noting both app and iOS 14+ DNS approaches have their nuances with how they play with VPN profiles (if you want to use both a VPN and separate encrypted DNS concurrently) but overall achieve the same thing.

**Comment by danarel** [comment]
I have opted to remove DNSCloack and in the next push, will include DNSecure. AdGuard Pro will likely be added in the future, and I know they have also recently announced [AdGuard-DNS](https://adguard-dns.com/en/welcome.html) which I have not used yet, but is on my watch list.
