### ISSUE TITLE
Not sure if this is the right forum

### ISSUE THREAD

**Issue by crspybits** [danarel/thinkprivacy#6]
Hi-- I like thinkprivacy.io! I'm not (yet) using any of the methods on https://www.thinkprivacy.io/contact.html so came here. I have a self-owned and private social media app, Neebla, recently on the Apple app store. https://itunes.apple.com/us/app/neebla/id1244482164?mt=8
The iOS app, and its server are open-source (e.g., see https://github.com/crspybits/SharedImages). I'm trying to get the word out about this and get some users for feedback. Right now, no business model but eventually I'll need to get some pricing (I'm thinking about a subscription on Apple's app store) to support the server costs which runs on AWS. I'm looking for venues to get links to the app. For example, if you think your page: https://www.thinkprivacy.io/socialmedia.html is appropriate, that would be great. Thanks!

**Comment by danarel** [comment]
It's too new right now to be recommended. Do you happen to have a privacy policy? I haven't looked at code yet, but are you using any analytics software in the app? What info does the app log?

**Comment by crspybits** [comment]
Hi @danarel. Nodding. The current privacy policy is here: 
http://www.spasticmuffin.biz/?page=Neebla&appPage=support
No analytics at this point. There are error logs in the iOS app, only sent to me by the user if they want to in a support request. There is logging in the server which is more extensive at this point as it's in development.

**Comment by danarel** [comment]
Thank you @crspybits 

I will keep an eye on this project!

**Comment by crspybits** [comment]
Cool! Thanks. I'm looking for forums and people get to know and to form connections with-- in relation to data privacy and ownership, and meetings/conferences to go to. Any thoughts would be appreciated.

**Comment by JonahAragon** [comment]
What are the benefits of Neebla over federated social networks like Mastodon and PixelFed? @crspybits if you're looking for forums to join I'm partial to https://forum.privacytools.io/ (being the admin and all).

**Comment by crspybits** [comment]
Perhaps you can tell me some about PixelFed. Searching, I'm not seeing much in the way of documentation. In terms of Neebla, it emphasizes individual ownership of media posted. You own the media because it gets stored in your own cloud storage. For example, an image you share in an album on Neebla gets uploaded to your own Google Drive or Dropbox. Plans are in the works to enable users to sign on with their own self-hosted cloud storage (e.g., ownCloud).
