### ISSUE TITLE
Mobile OS Clarifications & GrapheneOS Inclusion

### ISSUE THREAD

**Issue by JonahAragon** [danarel/thinkprivacy#8]
First, I just want to clarify what you recommend for mobile devices. You only list mobile applications with an iOS version, and you "don't recommend people use Android" (https://github.com/danarel/thinkprivacy/pull/7#issuecomment-497556684), so is your viewpoint that "people should use iOS", or is it that "people should not use mobile devices"?

If the former, I think iOS should be listed as a recommended Mobile OS for the sake of completion, and maybe a note that you recommend it over Android for [insert reasons here]. If the latter, I think that should be noted in the mobile section as well, that mobile devices shouldn't be used for [insert reasons here] and should be avoided in favor of Linux(?) wherever possible.

---

Secondly, I think GrapheneOS should probably be recommended as an Android ROM, above or even replacing LineageOS. We had a long discussion about this at https://github.com/privacytoolsIO/privacytools.io/issues/832 with some solid reasoning for its inclusion. Notably the following quote (from GrapheneOS dev @thestinger):

https://github.com/privacytoolsIO/privacytools.io/issues/832#issuecomment-488790013:
> I'm also not sure why you think basing it on LineageOS is a good idea when it has substantial security issues and major long-term issues of being dishonest with their users when it comes to privacy and security including lying about the security patch level (https://source.android.com/security/bulletin) to deceive users into thinking they're receiving full security updates.

This does appear to be the case because Android security patches fundamentally include device specific patches as well, so the security patch level *should* be an indicator that a device has received *all* the security patches up to the date listed. In reality LineageOS only appears to be incorporating whatever gets patched in the AOSP upstream and calling it good. Advertising devices that have never received any firmware/device-specific security patches as "secure" seems disingenuous on the part of the LineageOS team.

**Comment by danarel** [comment]
While I do recommend users not willing to install more hardened OSes on their phones use iOS over Android, the main reason all the tools are iOS is that I haven't added android specific ones yet.

One thing I have always tried to do is test apps myself and check them out before listing them and currently don't have access to an Android device I can do that with.

**Comment by danarel** [comment]
Added a little language recommending iOS over Android if someone is going with a mainstream OS, but also expanded the alternative OS selection for Android users. I also added some needed Android privacy related apps.

**Comment by thestinger** [comment]
I'd also recommend iOS as the best option for most users at this point. GrapheneOS is aiming to build a much better alternative, and it already has a lot of advantages, but there's a lot of work to do to further advance privacy and security along with making it much more usable for regular users. It's not yet at the point where including a nice set of bundled apps is a focus, and there's a lot of work to do on creating documentation. Many gaps from not including Google apps and services also need to be filled in. I have no issue with people having Google services as an option, but unfortunately their approach on Android is to make it all or nothing and there's absolutely no way that either Play Services or a reimplementation of it like microG would ever be included. Instead, the missing components will be replaced bit by bit with alternatives which is well underway along with providing a compatibility layer *not aiming to implementing clients for Google services* but rather just stubbing out anything with a hard dependency on them. For example, there's not going to be a Firebase Cloud Messaging client, but the API can certainly be stubbed out in a way that pretends the service is down / unavailable to make apps work.
